{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aa.bb",
    "module": "haha",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "haha-1.0.0.aar",
          "url": "haha-1.0.0.aar",
          "size": 43274,
          "sha512": "e34319df4ebfa81f8325618c7412fb2408456fe44a953ca9fe0a2227aa5874e70e652fd03b3456aafd80ededf9100fa308f4a11b9a1caf31ed73a678d00d55ec",
          "sha256": "6095dc90b2c9dbd75b29c291e34fabd2632d840b42a534d967e906f034ace19b",
          "sha1": "79e5a76a099f7998255fbff06837a185ff6b4391",
          "md5": "797d8176781e91442aff58bd56fb36d2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.amap.api",
          "module": "3dmap",
          "version": {
            "requires": "latest.integration"
          }
        },
        {
          "group": "com.amap.api",
          "module": "location",
          "version": {
            "requires": "latest.integration"
          }
        },
        {
          "group": "com.github.MRwangqi.MessageHook",
          "module": "hook",
          "version": {
            "requires": "1.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "haha-1.0.0.aar",
          "url": "haha-1.0.0.aar",
          "size": 43274,
          "sha512": "e34319df4ebfa81f8325618c7412fb2408456fe44a953ca9fe0a2227aa5874e70e652fd03b3456aafd80ededf9100fa308f4a11b9a1caf31ed73a678d00d55ec",
          "sha256": "6095dc90b2c9dbd75b29c291e34fabd2632d840b42a534d967e906f034ace19b",
          "sha1": "79e5a76a099f7998255fbff06837a185ff6b4391",
          "md5": "797d8176781e91442aff58bd56fb36d2"
        }
      ]
    }
  ]
}
