{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.MRwangqi",
    "module": "moduleRefPlugin",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "moduleRefPlugin-1.0.3.jar",
          "url": "moduleRefPlugin-1.0.3.jar",
          "size": 21791354,
          "sha512": "f6aa1afe2fae1e17d19ce37f655ecf5550c1a2e281f0d4e3a39e46258577fc02c6cc95d0f4e70ced344a78c406a599f360c9579df4de16d4cb0b6632de32940e",
          "sha256": "779097735912c09dbef858e6e30a97d87f1511729bfcf2a10033d9f02b4cfa6d",
          "sha1": "28320ed1a7192f1deb12e4ab041741245a0479f0",
          "md5": "5f4e5cade18d92ceecfd129a2389db4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "moduleRefPlugin-1.0.3.jar",
          "url": "moduleRefPlugin-1.0.3.jar",
          "size": 21791354,
          "sha512": "f6aa1afe2fae1e17d19ce37f655ecf5550c1a2e281f0d4e3a39e46258577fc02c6cc95d0f4e70ced344a78c406a599f360c9579df4de16d4cb0b6632de32940e",
          "sha256": "779097735912c09dbef858e6e30a97d87f1511729bfcf2a10033d9f02b4cfa6d",
          "sha1": "28320ed1a7192f1deb12e4ab041741245a0479f0",
          "md5": "5f4e5cade18d92ceecfd129a2389db4b"
        }
      ]
    }
  ]
}
