{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.MRwangqi",
    "module": "resourcePlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "resourcePlugin-1.0.0.jar",
          "url": "resourcePlugin-1.0.0.jar",
          "size": 8528,
          "sha512": "247755f756b37cdc89947cd604931beae04f2d8f3a0723e515375c7e3411c6884d0835c36739b940ee6ba6013d4d5e834d305bd56f06ca59a4139c41a2ae15ea",
          "sha256": "110e19a955ce43a54ad943e6a8e5124a0501bf520dadf8cc458d9d44a08a621d",
          "sha1": "87170632b7eed8c05926213d34e4c78a894028f3",
          "md5": "67447a076e5a08dfc35f23ba2f344323"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "resourcePlugin-1.0.0.jar",
          "url": "resourcePlugin-1.0.0.jar",
          "size": 8528,
          "sha512": "247755f756b37cdc89947cd604931beae04f2d8f3a0723e515375c7e3411c6884d0835c36739b940ee6ba6013d4d5e834d305bd56f06ca59a4139c41a2ae15ea",
          "sha256": "110e19a955ce43a54ad943e6a8e5124a0501bf520dadf8cc458d9d44a08a621d",
          "sha1": "87170632b7eed8c05926213d34e4c78a894028f3",
          "md5": "67447a076e5a08dfc35f23ba2f344323"
        }
      ]
    }
  ]
}
