{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.MRwangqi",
    "module": "modulePlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "modulePlugin-1.0.0.jar",
          "url": "modulePlugin-1.0.0.jar",
          "size": 9517,
          "sha512": "e73116b89905050cd0d6180fc16147c7b0f922f1f0a41ddb2c3140c3a3d7f4caf3d04bfcea2c174186e80fe88194deebe004be57f4349c2b946c57737587e2a3",
          "sha256": "646f1744817eecbcc8ca5918e82e31c2bfa3820d5db82c8a38bc1ef306530ae3",
          "sha1": "0e06abfac84df0d1f2938a1c2700652c1f276709",
          "md5": "31eef25f99d2063f695ac164ad97cc1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "modulePlugin-1.0.0.jar",
          "url": "modulePlugin-1.0.0.jar",
          "size": 9517,
          "sha512": "e73116b89905050cd0d6180fc16147c7b0f922f1f0a41ddb2c3140c3a3d7f4caf3d04bfcea2c174186e80fe88194deebe004be57f4349c2b946c57737587e2a3",
          "sha256": "646f1744817eecbcc8ca5918e82e31c2bfa3820d5db82c8a38bc1ef306530ae3",
          "sha1": "0e06abfac84df0d1f2938a1c2700652c1f276709",
          "md5": "31eef25f99d2063f695ac164ad97cc1f"
        }
      ]
    }
  ]
}
