{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.MRwangqi",
    "module": "lint",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "lint-1.0.0.aar",
          "url": "lint-1.0.0.aar",
          "size": 10980,
          "sha512": "63a803afb213e5340d0acf8449c6518ba5a5141e00d6414579f4dbcbad6f3f1305fc1e91997e565d3e11447bfe7e2113bbb011087a424120fa63a2284db641dc",
          "sha256": "4a1d96f8ffb79aabbb6a8c442f74a223702d3147f0c268165099fc7447d5931d",
          "sha1": "0d7ce8efd2b269546c6b7a7449b19507d8bc1e1e",
          "md5": "8ed4434cb6920ccda5b28379e123e0d9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "lint-1.0.0.aar",
          "url": "lint-1.0.0.aar",
          "size": 10980,
          "sha512": "63a803afb213e5340d0acf8449c6518ba5a5141e00d6414579f4dbcbad6f3f1305fc1e91997e565d3e11447bfe7e2113bbb011087a424120fa63a2284db641dc",
          "sha256": "4a1d96f8ffb79aabbb6a8c442f74a223702d3147f0c268165099fc7447d5931d",
          "sha1": "0d7ce8efd2b269546c6b7a7449b19507d8bc1e1e",
          "md5": "8ed4434cb6920ccda5b28379e123e0d9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lint-1.0.0-sources.jar",
          "url": "lint-1.0.0-sources.jar",
          "size": 683,
          "sha512": "0681ed977f433f45fc9a792b57e37bd6b3f3964ec2cf9dee2e54a3b4a7574babff846e7f358bb19ae5ba8d618f57445b087a63dc9ef41e5862a75c920cb784f9",
          "sha256": "9eb4c74968cdbb8a226d4cb0b306b38e9f590c5195ed252daaedf8e28788e261",
          "sha1": "2a5fddab155fa4188d539289530486c48351a9ca",
          "md5": "af98f344c688269f4988ac097de1fca5"
        }
      ]
    }
  ]
}
