{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codelang.jitpack",
    "module": "hook-test",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "hook-test-1.0.aar",
          "url": "hook-test-1.0.aar",
          "size": 33175,
          "sha512": "8c8e8d8166fb06bad94cb0b93a5c6f539fa5ce3245472dcc1a89f93d6644ff6f85bd11e16a31ae060d3c885646aae9e8badd6836e17a620e0cd8a40bd268dc56",
          "sha256": "441b8089f28420049580c596622db66267db863bbf3b994e7996abbc38e6d6db",
          "sha1": "d18739a4c589cf6f8d1fe43f537de1dffc895a7f",
          "md5": "9f35be86e0c854274ff67b461ae2a5ab"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "hook-test-1.0.aar",
          "url": "hook-test-1.0.aar",
          "size": 33175,
          "sha512": "8c8e8d8166fb06bad94cb0b93a5c6f539fa5ce3245472dcc1a89f93d6644ff6f85bd11e16a31ae060d3c885646aae9e8badd6836e17a620e0cd8a40bd268dc56",
          "sha256": "441b8089f28420049580c596622db66267db863bbf3b994e7996abbc38e6d6db",
          "sha1": "d18739a4c589cf6f8d1fe43f537de1dffc895a7f",
          "md5": "9f35be86e0c854274ff67b461ae2a5ab"
        }
      ]
    }
  ]
}
