{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.MRwangqi",
    "module": "runtimecheck",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtimecheck-1.0.0.aar",
          "url": "runtimecheck-1.0.0.aar",
          "size": 12046,
          "sha512": "ba0ee4a808790190e32908dc1afee1399c24152d9c8f3a645ed83539119d181740a3938f4e9e114436837856ca4ceda861cd2f84bb1c81e945f54f0eb63221e2",
          "sha256": "dba6f1952e1b935136584a0fb919a4ea9300ebfcdbec1b13ed0b15fd906c4c17",
          "sha1": "0892a323d9974ba582b7ff59de51a391c8458c85",
          "md5": "34de0c0784a4585ca3563c182446ae93"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "top.canyie.pine",
          "module": "core",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtimecheck-1.0.0.aar",
          "url": "runtimecheck-1.0.0.aar",
          "size": 12046,
          "sha512": "ba0ee4a808790190e32908dc1afee1399c24152d9c8f3a645ed83539119d181740a3938f4e9e114436837856ca4ceda861cd2f84bb1c81e945f54f0eb63221e2",
          "sha256": "dba6f1952e1b935136584a0fb919a4ea9300ebfcdbec1b13ed0b15fd906c4c17",
          "sha1": "0892a323d9974ba582b7ff59de51a391c8458c85",
          "md5": "34de0c0784a4585ca3563c182446ae93"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtimecheck-1.0.0-sources.jar",
          "url": "runtimecheck-1.0.0-sources.jar",
          "size": 4855,
          "sha512": "5c77e2b430df6d39885e716ab7aa0682113f26b530737a6ca5341dca7e54e7a81accd7864469c59e9418c27b56ab95378ea170b750db006f6b819e9b7ca88232",
          "sha256": "ffb4e57751e098d385157a60d207ac14a4d18d5e73a777efe13af456a957f6a0",
          "sha1": "671493c3b2d8cc36d412c35e49ad11ff39728826",
          "md5": "96b482117689f51f4111ecf5b81688ed"
        }
      ]
    }
  ]
}
