{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.MRwangqi",
    "module": "runtimecheck",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtimecheck-1.0.0.aar",
          "url": "runtimecheck-1.0.0.aar",
          "size": 12731,
          "sha512": "95759cbb2102af6493f049f2c6c00766172f84d402fc1e4cc946c353077814a6ba57fb2c383d70153e11cd3a20511d6268da9c1b26437157763c34896cd66c2c",
          "sha256": "25777dbbec521a6ab17503a8f7a59a24a15b1a797f6baa8913c7b3a8b2b926d8",
          "sha1": "78d0eabf293d8ea7734cf3f9d8b68c452ca24d55",
          "md5": "e5f31f8a6b8f6a2e97cf91476018298a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "top.canyie.pine",
          "module": "core",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "runtimecheck-1.0.0.aar",
          "url": "runtimecheck-1.0.0.aar",
          "size": 12731,
          "sha512": "95759cbb2102af6493f049f2c6c00766172f84d402fc1e4cc946c353077814a6ba57fb2c383d70153e11cd3a20511d6268da9c1b26437157763c34896cd66c2c",
          "sha256": "25777dbbec521a6ab17503a8f7a59a24a15b1a797f6baa8913c7b3a8b2b926d8",
          "sha1": "78d0eabf293d8ea7734cf3f9d8b68c452ca24d55",
          "md5": "e5f31f8a6b8f6a2e97cf91476018298a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtimecheck-1.0.0-sources.jar",
          "url": "runtimecheck-1.0.0-sources.jar",
          "size": 5137,
          "sha512": "37a98ba91a4d8cb8b244dc8aaca0b0ffcabf5cd159fb850e5be95ad711613b61e62390e8a9b334235e5bcb5dec48805f14c29dc72cfadff338732a8d4e050cff",
          "sha256": "b42aa8d5cb428ab0b7e55a0c83c0046d5c199f233a3e94a0d41321f3ec8b102d",
          "sha1": "0218adb7cf979a5a29d024fb1c7b29188ebf0f7a",
          "md5": "df7b57df9549f92475a4c663618a4017"
        }
      ]
    }
  ]
}
