{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.MRwangqi",
    "module": "fridacheck",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "fridacheck-1.0.0.aar",
          "url": "fridacheck-1.0.0.aar",
          "size": 18056817,
          "sha512": "d03a7ea2ab7c71ffcd8b680eb98162b23b6431f3a1d072b721d62d4f72a1dc45c4a29dbbb8fb723f9efefdf8883f5032855bd6cc0d94db0fe0c97094189c22d3",
          "sha256": "f9c4cf9ce2a38567b6469cb257e47e59fe0427ba4d61278b011abb84336b5b58",
          "sha1": "4f3caf478177b9b86df8d0a58cd6704c952a07c9",
          "md5": "576e9a80b91325e5b60cf56be8494b52"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "fridacheck-1.0.0.aar",
          "url": "fridacheck-1.0.0.aar",
          "size": 18056817,
          "sha512": "d03a7ea2ab7c71ffcd8b680eb98162b23b6431f3a1d072b721d62d4f72a1dc45c4a29dbbb8fb723f9efefdf8883f5032855bd6cc0d94db0fe0c97094189c22d3",
          "sha256": "f9c4cf9ce2a38567b6469cb257e47e59fe0427ba4d61278b011abb84336b5b58",
          "sha1": "4f3caf478177b9b86df8d0a58cd6704c952a07c9",
          "md5": "576e9a80b91325e5b60cf56be8494b52"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fridacheck-1.0.0-sources.jar",
          "url": "fridacheck-1.0.0-sources.jar",
          "size": 5067,
          "sha512": "24a4abb623b436fbb75959ecca8558d3335e6e5ee2e11dd6f56497d291b294a3ffbfda100844d04cda7bd5f9f7846974a378af9ad9da204489cacd9834bb9fe4",
          "sha256": "9ae948aa1127c3b3afc1e4c4d52ca9c8d6d0a06e5551771536b7bc7b7ac3a2a2",
          "sha1": "a6db21548f840801ae0ade676acdc22ef63e9547",
          "md5": "2bffd0f6443ddd19a7fa0a2cce439a91"
        }
      ]
    }
  ]
}
