{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.MRwangqi",
    "module": "fridacheck",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "fridacheck-1.0.0.aar",
          "url": "fridacheck-1.0.0.aar",
          "size": 18056276,
          "sha512": "81b566cf38de6ea325af12f9f800f7da2f44d011723954035b288caacf81f7a7812d08c039df34fb8a60ecba5d354a6464153203599d6eb9724d76f79cb4dfee",
          "sha256": "76f4bc80e900527d9bc09188f33eb8ee7c470f79c4ff2f189ed49d2d661327f1",
          "sha1": "398483e87fd9c27264ef620b355df2a6f1e32d35",
          "md5": "d72cc46d3a25d762cc0659b058a2ee2d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "fridacheck-1.0.0.aar",
          "url": "fridacheck-1.0.0.aar",
          "size": 18056276,
          "sha512": "81b566cf38de6ea325af12f9f800f7da2f44d011723954035b288caacf81f7a7812d08c039df34fb8a60ecba5d354a6464153203599d6eb9724d76f79cb4dfee",
          "sha256": "76f4bc80e900527d9bc09188f33eb8ee7c470f79c4ff2f189ed49d2d661327f1",
          "sha1": "398483e87fd9c27264ef620b355df2a6f1e32d35",
          "md5": "d72cc46d3a25d762cc0659b058a2ee2d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fridacheck-1.0.0-sources.jar",
          "url": "fridacheck-1.0.0-sources.jar",
          "size": 4767,
          "sha512": "946c20df6ebe9310e986fe9b43e1e5b5096b2b47d02749d4a827ae33cfc9ecc116ab870a833ba701c1a59a943274a168dbdc5ceec0e9837e57a5f2cc7807af53",
          "sha256": "40dbd48d5b696d4f5ef2542492b97fed34b54fe1ced427bb0fd9238639c36a2d",
          "sha1": "86fc1cc82a538694c0fdd663c5b854e086641025",
          "md5": "cec4a864c794bfd483b17a74545539ef"
        }
      ]
    }
  ]
}
