{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.MRwangqi",
    "module": "fridacheck",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "fridacheck-1.0.0.aar",
          "url": "fridacheck-1.0.0.aar",
          "size": 18056153,
          "sha512": "5adc78243b98145a58ec7db44b4e32c9faa2d17fe5f850072216be0cdf2179ed1ee03bf1ae43b347ecdb8cb8ad32ca07b18bda8c4a06ff87a792a92539bb2302",
          "sha256": "47d4a8be8faff9742c4fc86a5e4f900f86839eda06d9e3df37301763448b1e14",
          "sha1": "6e09c37c9637ba63f90b5d580f040f9532cc16d4",
          "md5": "813c75dd29882c2f0c7bcd9c7def0f0a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "fridacheck-1.0.0.aar",
          "url": "fridacheck-1.0.0.aar",
          "size": 18056153,
          "sha512": "5adc78243b98145a58ec7db44b4e32c9faa2d17fe5f850072216be0cdf2179ed1ee03bf1ae43b347ecdb8cb8ad32ca07b18bda8c4a06ff87a792a92539bb2302",
          "sha256": "47d4a8be8faff9742c4fc86a5e4f900f86839eda06d9e3df37301763448b1e14",
          "sha1": "6e09c37c9637ba63f90b5d580f040f9532cc16d4",
          "md5": "813c75dd29882c2f0c7bcd9c7def0f0a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fridacheck-1.0.0-sources.jar",
          "url": "fridacheck-1.0.0-sources.jar",
          "size": 4763,
          "sha512": "35e542a5250e2da59ceab03e32417c8309c9ae4cbf2bbb62423358e371d1f68a9584e604dbdc42c3517817ae0e60672b8dc859abb1f4b1193f1e48a8dfaae304",
          "sha256": "1ef093dfaa5948e492b72047c725b57a4f400a0075a3b587b99f3e62eeaa3932",
          "sha1": "77672dc72f70a942473cc9c1a51ffaa3f63bab56",
          "md5": "d305d75e92426d2ab6a2550a5eb26808"
        }
      ]
    }
  ]
}
