{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin",
    "module": "classAnalysis",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "classAnalysis-1.0.0.jar",
          "url": "classAnalysis-1.0.0.jar",
          "size": 249937,
          "sha512": "b1fac123cfcb3970ddb5d0ab33ee50b5e53ca6b3c18cf2870586f5038990ba6d7c93ebd60ae627dc7867e3a5a94eeacbfcc8dbf2eeb57b882d01c9ad89a0c7a9",
          "sha256": "872da44950e01cb7c883b8759025cf059b74d10fb7e2ca5c1e132210168764df",
          "sha1": "f790b1e9597c4b58764b1c5a81e25d2abc7e31c3",
          "md5": "f263d15a6cfce9171db9d5e3276f00f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "classAnalysis-1.0.0.jar",
          "url": "classAnalysis-1.0.0.jar",
          "size": 249937,
          "sha512": "b1fac123cfcb3970ddb5d0ab33ee50b5e53ca6b3c18cf2870586f5038990ba6d7c93ebd60ae627dc7867e3a5a94eeacbfcc8dbf2eeb57b882d01c9ad89a0c7a9",
          "sha256": "872da44950e01cb7c883b8759025cf059b74d10fb7e2ca5c1e132210168764df",
          "sha1": "f790b1e9597c4b58764b1c5a81e25d2abc7e31c3",
          "md5": "f263d15a6cfce9171db9d5e3276f00f5"
        }
      ]
    }
  ]
}
