{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin",
    "module": "classAnalysis",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "classAnalysis-1.0.0.jar",
          "url": "classAnalysis-1.0.0.jar",
          "size": 249981,
          "sha512": "ad11aba7aea7d5d772aa2623e911a34391bc40d2d196606aaf5f4dccceb2837135689f470bbf4c2f66c903cff56cfb06bc0637e15ca60895320f68df4ce89e36",
          "sha256": "bd59afd38c275c1f4aff19d2fd71d746df23440ad0f02bfdff5c92a7c77336e9",
          "sha1": "6d9eac16bf0f2d691b8a9bfa6338215348b299a9",
          "md5": "ef3217e833fad254f168d1cda6cadc43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "classAnalysis-1.0.0.jar",
          "url": "classAnalysis-1.0.0.jar",
          "size": 249981,
          "sha512": "ad11aba7aea7d5d772aa2623e911a34391bc40d2d196606aaf5f4dccceb2837135689f470bbf4c2f66c903cff56cfb06bc0637e15ca60895320f68df4ce89e36",
          "sha256": "bd59afd38c275c1f4aff19d2fd71d746df23440ad0f02bfdff5c92a7c77336e9",
          "sha1": "6d9eac16bf0f2d691b8a9bfa6338215348b299a9",
          "md5": "ef3217e833fad254f168d1cda6cadc43"
        }
      ]
    }
  ]
}
