{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin",
    "module": "checkPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "checkPlugin-1.0.0.jar",
          "url": "checkPlugin-1.0.0.jar",
          "size": 57042,
          "sha512": "70f686e38916109f28c6022b73c12c8ce29bd2d140251a0ef3b949b09dd4717ee4408de59c2ebfbc1b519b1cba3a8015aa2d8bd6f63d42d92f0c01673a3d512f",
          "sha256": "586f413c03af5a147a4f88e3844c63548b8f75ee836bf7ecd733f78015cfd3b3",
          "sha1": "6ff968f3645d66c1978ea9c3e6bbbdee3fcdaf49",
          "md5": "5d412e909e092fd5fddfc75c596883b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "checkPlugin-1.0.0.jar",
          "url": "checkPlugin-1.0.0.jar",
          "size": 57042,
          "sha512": "70f686e38916109f28c6022b73c12c8ce29bd2d140251a0ef3b949b09dd4717ee4408de59c2ebfbc1b519b1cba3a8015aa2d8bd6f63d42d92f0c01673a3d512f",
          "sha256": "586f413c03af5a147a4f88e3844c63548b8f75ee836bf7ecd733f78015cfd3b3",
          "sha1": "6ff968f3645d66c1978ea9c3e6bbbdee3fcdaf49",
          "md5": "5d412e909e092fd5fddfc75c596883b3"
        }
      ]
    }
  ]
}
