{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin",
    "module": "moduleRefPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "moduleRefPlugin-1.0.0.jar",
          "url": "moduleRefPlugin-1.0.0.jar",
          "size": 21791224,
          "sha512": "150f0924b0fea66e8fc0405e0675c82bd2b4fb349cc6c44a3dde34f751dd6d29bd15a34b923ebb9439e9d4e3c1142a9e79db6ecb71cfa850611299c8799e1244",
          "sha256": "0b72c0f9b7f473c3b7b553a6304885b8d9e21f7ea87199ba75a626de149b214a",
          "sha1": "26b4eb941de1e7078a4dfbb14412f0d08c6338f3",
          "md5": "e3659f94a805af336615e61e1fe17757"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "moduleRefPlugin-1.0.0.jar",
          "url": "moduleRefPlugin-1.0.0.jar",
          "size": 21791224,
          "sha512": "150f0924b0fea66e8fc0405e0675c82bd2b4fb349cc6c44a3dde34f751dd6d29bd15a34b923ebb9439e9d4e3c1142a9e79db6ecb71cfa850611299c8799e1244",
          "sha256": "0b72c0f9b7f473c3b7b553a6304885b8d9e21f7ea87199ba75a626de149b214a",
          "sha1": "26b4eb941de1e7078a4dfbb14412f0d08c6338f3",
          "md5": "e3659f94a805af336615e61e1fe17757"
        }
      ]
    }
  ]
}
