{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin",
    "module": "moduleRefPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "moduleRefPlugin-1.0.0.jar",
          "url": "moduleRefPlugin-1.0.0.jar",
          "size": 21791237,
          "sha512": "b056a5a12eae66274de09ad873fb31d5bcf1e79aa5b01f8712ced0b3014e4fe158fbf6b8638eca072885493101f075ce98421f3007ad7e13b3f02b91f579fa9e",
          "sha256": "04d7a8e112556f679618b0a1749f26eb128fb6fa8c2c98be67d6a86adcff31f3",
          "sha1": "170e27dd4f21c22a543d7cd8c5558328894d7a6a",
          "md5": "4cee6b9a8c91fbe32c5a5e00293a9345"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "moduleRefPlugin-1.0.0.jar",
          "url": "moduleRefPlugin-1.0.0.jar",
          "size": 21791237,
          "sha512": "b056a5a12eae66274de09ad873fb31d5bcf1e79aa5b01f8712ced0b3014e4fe158fbf6b8638eca072885493101f075ce98421f3007ad7e13b3f02b91f579fa9e",
          "sha256": "04d7a8e112556f679618b0a1749f26eb128fb6fa8c2c98be67d6a86adcff31f3",
          "sha1": "170e27dd4f21c22a543d7cd8c5558328894d7a6a",
          "md5": "4cee6b9a8c91fbe32c5a5e00293a9345"
        }
      ]
    }
  ]
}
