{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin",
    "module": "moduleRefPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "moduleRefPlugin-1.0.0.jar",
          "url": "moduleRefPlugin-1.0.0.jar",
          "size": 21791181,
          "sha512": "38d5df02625bb9bb51c5008d47988b6d8d9aa4b0ad61d5c4de1f5ca223a42e769af525161d653deefc52f25fd3280be09182847ba06fcc5a2f907d041c4acd87",
          "sha256": "7b7e6562a91ff01a2a57018314c24af7450f11d8a8668884e7a10acda691daf2",
          "sha1": "a0a91eb5f41739f56287b2f48c37703e67b167ca",
          "md5": "5417c943617ca77c41fa501235e6f24c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "moduleRefPlugin-1.0.0.jar",
          "url": "moduleRefPlugin-1.0.0.jar",
          "size": 21791181,
          "sha512": "38d5df02625bb9bb51c5008d47988b6d8d9aa4b0ad61d5c4de1f5ca223a42e769af525161d653deefc52f25fd3280be09182847ba06fcc5a2f907d041c4acd87",
          "sha256": "7b7e6562a91ff01a2a57018314c24af7450f11d8a8668884e7a10acda691daf2",
          "sha1": "a0a91eb5f41739f56287b2f48c37703e67b167ca",
          "md5": "5417c943617ca77c41fa501235e6f24c"
        }
      ]
    }
  ]
}
