{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin",
    "module": "uploadPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "uploadPlugin-1.0.0.jar",
          "url": "uploadPlugin-1.0.0.jar",
          "size": 25615,
          "sha512": "7f0125b72e2c637414e084bb035251e216979a3b60253053f9392edd0a6e98047bd264990a0b039eefc2ee6ab15caeb7443755234be1ef5d06d33fdc89febe5a",
          "sha256": "6ffb910d145ef645eaa80af3050fdca4c52740b6737b8c388d24f3725ff15526",
          "sha1": "0665b7276791548863ebd4b70d6446feef9a50bf",
          "md5": "87fc85035e14f967e4bc2b455ae4ca83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.1.0.202203080745-r"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "uploadPlugin-1.0.0.jar",
          "url": "uploadPlugin-1.0.0.jar",
          "size": 25615,
          "sha512": "7f0125b72e2c637414e084bb035251e216979a3b60253053f9392edd0a6e98047bd264990a0b039eefc2ee6ab15caeb7443755234be1ef5d06d33fdc89febe5a",
          "sha256": "6ffb910d145ef645eaa80af3050fdca4c52740b6737b8c388d24f3725ff15526",
          "sha1": "0665b7276791548863ebd4b70d6446feef9a50bf",
          "md5": "87fc85035e14f967e4bc2b455ae4ca83"
        }
      ]
    }
  ]
}
