{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin",
    "module": "uploadPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "uploadPlugin-1.0.0.jar",
          "url": "uploadPlugin-1.0.0.jar",
          "size": 25324,
          "sha512": "3993a7bfb3e7367f013bd5894a69ab2a656a144a8f052e166a0bca87cd7e8d2224f56bbe4e16f46e575f5c4ee6af74da81fd5daf11a1ab11d7002bb489ebc8d0",
          "sha256": "35708d0071907cdce39e19a74b32cf40a176ded5cd4f4c665f2ce3679e2bc5bb",
          "sha1": "808c6b0b4e73a3134f10f7503f416b81f8eac36c",
          "md5": "2478812aa41f72c0526c65f2063b302d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.1.0.202203080745-r"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "uploadPlugin-1.0.0.jar",
          "url": "uploadPlugin-1.0.0.jar",
          "size": 25324,
          "sha512": "3993a7bfb3e7367f013bd5894a69ab2a656a144a8f052e166a0bca87cd7e8d2224f56bbe4e16f46e575f5c4ee6af74da81fd5daf11a1ab11d7002bb489ebc8d0",
          "sha256": "35708d0071907cdce39e19a74b32cf40a176ded5cd4f4c665f2ce3679e2bc5bb",
          "sha1": "808c6b0b4e73a3134f10f7503f416b81f8eac36c",
          "md5": "2478812aa41f72c0526c65f2063b302d"
        }
      ]
    }
  ]
}
