{
  "formatVersion": "1.1",
  "component": {
    "group": "plugin",
    "module": "checkPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "checkPlugin-1.0.1.jar",
          "url": "checkPlugin-1.0.1.jar",
          "size": 57068,
          "sha512": "c96d0dfef3391bcc132232ac019f1f905b269d3f87d6f7183cd51188ffebd5459713969be337de9cef414c53fa42b36d0a2b18323994c69cd9136328fd390b7f",
          "sha256": "1fc6708d2e8fb487514a10afa8b40589dabd5a7bd410f3cc1757cc061d810ec4",
          "sha1": "dbc80a5905900af63ccf8730e41d1ec5917e8c83",
          "md5": "b3cd0415c49927ccf1fea5fb5d30e99f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "checkPlugin-1.0.1.jar",
          "url": "checkPlugin-1.0.1.jar",
          "size": 57068,
          "sha512": "c96d0dfef3391bcc132232ac019f1f905b269d3f87d6f7183cd51188ffebd5459713969be337de9cef414c53fa42b36d0a2b18323994c69cd9136328fd390b7f",
          "sha256": "1fc6708d2e8fb487514a10afa8b40589dabd5a7bd410f3cc1757cc061d810ec4",
          "sha1": "dbc80a5905900af63ccf8730e41d1ec5917e8c83",
          "md5": "b3cd0415c49927ccf1fea5fb5d30e99f"
        }
      ]
    }
  ]
}
